version: '3'
services:
  nodejs-apiservice:
    build: 
      context: .
      dockerfile: api-service/Dockerfile
    image: nodejs-apiservice
    container_name: nodejs-apiservice
    entrypoint: /usr/src/app/entrypoint.sh
    ports:
      - "3000:3001"
    volumes:
      - ./api-service:/usr/src/app
    networks:
      - nginx_network
    depends_on:
      - nodejs-redis

  nodejs-redis:
    build: 
      context: .
      dockerfile: redis/Dockerfile
    image: nodejs-redis
    container_name: nodejs-redis
    ports:
      - "6379:6379"
    networks:
      - nginx_network
  
  nodejs-stockservice:
    build: 
      context: .
      dockerfile: stock-service/Dockerfile
    image: nodejs-stockservice
    container_name: nodejs-stockservice
    entrypoint: /usr/src/app/entrypoint.sh
    ports:
      - "3002:3002"
    volumes:
      - ./stock-service:/usr/src/app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge 